--
author: sloth
email: tingyi_li@brown.edu
description:  tjkjk
twitter_username: nkjk
github_username:  jj
show_excerpts: true # set to false to remove excerpts on the homepage
title: strawberry
theme: minima

date: 2019-09-07


--
