@@ -1,13 +1,22 @@
--
title: Your awesome title
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
title: bb
email:bb@brown.edu
description: >- # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for

twitter_username: kjk
github_username:  nkjk
twitter_username: nbmnm
github_username: kjk
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
theme: minima
plugins:
  - jekyll-feed
show_excerpts: true # set to false to remove excerpts on the homepage
--
